use cabbookinganalysis;
SHOW TABLES;
SELECT * FROM bookings;
SELECT * FROM Customers;
SELECT * FROM cabs;
SELECT * FROM drivers;
SELECT * FROM tripdetails;



# Revenue & Business Metrics - 
# Q1) 1. Identify customers who have completed the most bookings. 
   # What insights can you draw about their behavior?
   
select customer_id,name,count(booking_id) from Customers join bookings
 using(customer_id) group by customer_id order by count(*) desc;
 
 # Q2) 2. Find customers who have canceled more than 30% of their total bookings. 
 # What could be the reason for frequent cancellations?
 select * from customers;
 select * from bookings;
 select c. customer_id, c. name, c. phone_number, count(b.booking_id) as total;
select * from bookings;
SELECT booking_id, customer_id, status, cancellation_reason FROM bookings
WHERE status = 'cancelled ' ;
select * from cte where     
#Q3) Determine the busiest day of the week for bookings How can the company optimize cab availability on peak days?
SHOW TABLES;
SELECT * FROM BOOKINGS;
SELECT * FROM CABS;
SELECT dayname(booking_date) as day_of_week, count(*) as total_bookings from bookings
group by dayname(booking_date) order by total_bookings desc;

#Operational Efficiency & Optimization - 
#Q1)Operational Efficiency & Optimization
# 1.1. Identify drivers who have received an average rating below 3.0 in the
# past three months. What strategies can be implemented to improve their performance?
select* FROM BOOKINGS;
SELECT * FROM CABS;
show tables;
SELECT d.driver_id, d.name AS driver_name, ROUND(AVG(f.customer_rating), 2) AS avg_rating
FROM Drivers d
JOIN Cabs c ON d.driver_id = c.driver_id
JOIN Bookings b ON c.cab_id = b.cab_id
JOIN Feedback f ON b.booking_id = f.booking_id
WHERE b.booking_date >= DATE_SUB(CURDATE(), INTERVAL 3 MONTH)
GROUP BY d.driver_id, d.name
HAVING avg_rating < 3.0;

# 2. Find the top 5 drivers who have completed the longest trips in terms of distance.
#  What does this say about their working patterns
select* FROM BOOKINGS;
SELECT * FROM CABS;
SELECT * FROM DRIVERS;
SELECT * FROM TRIPDETAILS;
SHOW TABLES ;

SELECT d.driver_id, d.name as driver_name, d.rating,  t.distance_km as total_distance from drivers 
join cabs c on d.driver_id = c.driver_id 
join bookings b on c.cab_id = b.cab_id
join tripdetails t on b.booking_id = t. booking_id
where b.status = 'completed'
group by d.driver_id, d.name desc
order by total_distance DESC 
LIMIT 5 ;

# Q.3) Identify drivers with a high percentage of canceled trips. Could this indicate driver unreliability?
select * FROM BOOKINGS;
SELECT * FROM CABS;
SELECT * FROM DRIVERS;
SELECT * FROM TRIPDETAILS;
select * from customers;
    
SELECT d.driver_id, d.name AS driver_name,
    COUNT(b.booking_id) AS total_trips,
    SUM(CASE WHEN b.status = 'Cancelled' THEN 1 ELSE 0 END) AS cancelled_trips,
    ROUND((SUM(CASE WHEN b.status = 'Cancelled' THEN 1 ELSE 0 END) / COUNT(b.booking_id)) * 100,2) AS cancel_percentage
FROM Drivers d
JOIN Cabs c ON d.driver_id = c.driver_id
JOIN Bookings b ON c.cab_id = b.cab_id
GROUP BY d.driver_id, d.name
HAVING cancel_percentage > 0  
ORDER BY cancel_percentage DESC;

# Revenue & Business Metrics 
# Q1. Calculate the total revenue generated by completed bookings in the last 6 months. 
# How has the revenue trend changed over time?
select * FROM BOOKINGS;
SELECT * FROM TRIPDETAILS;

SELECT DATE_FORMAT(b.booking_date, '%Y-%m') AS month,
    SUM(t.fare_amount) AS monthly_revenue
FROM TripDetails t
JOIN Bookings b ON t.booking_id = b.booking_id
WHERE booking_date >= DATE_SUB(CURDATE(), INTERVAL 6 MONTH)
GROUP BY DATE_FORMAT(b.booking_date, '%Y-%m')
ORDER BY month;

# Q2. 2. Identify the top 3 most frequently traveled routes based on PickupLocation and DropoffLocation. 
# Should the company allocate more cabs to these routes?
SHOW TABLES;
SELECT * FROM bookings;
SELECT * FROM Customers;

SELECT pickup_location, dropoff_location, 
count(*) as total_trips from bookings 
where status = 'completed'
group by pickup_location, dropoff_location
ORDER BY total_trips desc LIMIT 3 ;

#3. Determine if higher-rated drivers tend to complete more trips and earn higher fares. 
# Is there a direct correlation between driver ratings and earnings?

select * FROM BOOKINGS;
SELECT * FROM DRIVERS;
SELECT * FROM TRIPDETAILS;
SELECT * FROM cabs;

SELECT d.driver_id, d.name as drivernam, d.rating, 
count(t.trip_id) as total_trips, 
sum(t.fare_amount) as total_earn from  drivers d 
join cabs c on d.driver_id = c.driver_id 
join bookings b on b.cab_id = c.cab_id 
join tripdetails t on b.booking_id = t.booking_id 
where b.status = 'completed'
group by d.driver_id, d.name, d.rating
order by d.rating desc limit 4 ;

# . Operational Efficiency & Optimization 
# Q1. Analyze the average waiting time (difference between booking time and trip start time) for different pickup locations. 
# How can this be optimized to reduce delays?
select * FROM BOOKINGS;
SELECT * FROM TRIPDETAILS;

select b.pickup_location, avg(timestampdiff(MINUTE,b.booking_date,t.trip_start_time )) as averagewaitime
from bookings b join TRIPDETAILS t on t.booking_id = b.booking_id
where status = 'completed'
group by b.pickup_location 
order by averagewaitime desc; 
SHOW TABLES;
SELECT * FROM DRIVERS;
SELECT * FROM TRIPDETAILS;
select * from customers;
select * from cabs;
select * from bookings;
# Q.2) Identify the most common reasons for trip cancellations from customer feedback. 
# What actions can be taken to reduce cancellations? 

select cancellation_reason as reason, status, count(*) as total_cancellation
from bookings where status = 'Cancelled'
group by reason 
order by total_cancellation desc;

#Q.3 ) 3. Find out whether shorter trips (low-distance) contribute significantly to revenue. 
# Should the company encourage more short-distance rides?

select * from customers;
select booking_id, distance_km, fare_amount as totalrev
 from TRIPDETAILS order by distance_km ;
 
 #  Comparative & Predictive Analysis
 # Q1. Compare the revenue generated from 'Sedan' and 'SUV' cabs. 
 # Should the company invest more in a particular vehicle type?
 show tables;
select * FROM BOOKINGS;
SELECT * FROM CABS;
SELECT * FROM DRIVERS;
SELECT * FROM TRIPDETAILS;

select b.booking_id, b.status, t.distance_km, t.fare_amount, c.cab_id, c.cab_type
 from bookings b 
 join TRIPDETAILS t on b.booking_id = t.booking_id
 join cabs c on c.cab_id = b.cab_id
 where c.cab_type = 'Sedan' order by t.fare_amount desc;
 
# 2. Predict which customers are likely to stop using the service based on their last booking date and frequency of rides.
# How can customer retention be improved?
select * from customers;
select * from bookings;
select * from tripdetails;
select  c.name ,c.phone_number, c.email, b.status , b.wait_time_minutes, b.booking_date 
from customers c join bookings b on b.customer_id = c.customer_id 
order by b.booking_date desc;

# 3. Analyze whether weekend bookings differ significantly from weekday bookings.
# Should the company introduce dynamic pricing based on demand?
select * from customers;
select * from bookings;
select * from tripdetails;
select case when dayofweek(b.booking_date) in (1,7) then 'Weekend' else 'weekday' end as date_type,
count(*) as total_bookings, sum(t.fare_amount) as total_rev, b.status
from bookings b join tripdetails t on t.booking_id = b.booking_id 
where b.status = 'completed'
group by date_type;








    
    

 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
